### ISSUE TITLE
Error when using annotate

### ISSUE THREAD

**Issue by MerAlDa99** [simonwm/tacco#12]
When I try to use the annotate function on my own slide-seq data with my own annotated reference I run into the error: 
![image](https://github.com/simonwm/tacco/assets/135689183/54d40bc7-f102-4200-91eb-832383b75e32)
I am unsure what is causing this, but somehow it seems like the variables are not found in the datasets: 
![image](https://github.com/simonwm/tacco/assets/135689183/3fdaa459-ebd3-4215-a867-aa320724e88c)

**Comment by JWatter** [comment]
Hi,
it seems that all of the genes in your data got filtered out completely ("There is no expression data available in the 'reference'", screenshot 1). From your 2. screenshot we see that both anndatas do contain genes, but they dont get passed on to annotate (see screenshot 1: "Starting annotation of data with shape (51258,0 ) and a reference of shape (41663, 0)"). Tacco only uses genes that have the same name in both data sets. Maybe the gene names follow different conventions, e.g. human gene names in the reference and mouse gene names in slide-seq? You could print out some gene names or look at the intersection of the `.var_names` of both data sets. If this does not help we might need to look at the expression matrices.
Hope this helps!
