### ISSUE TITLE
Raw counts data as reference or normalized data as reference?

### ISSUE THREAD

**Issue by parkjooyoung99** [simonwm/tacco#2]
Hello, 

I am using sc reference data processed via Seurat. While extracting expression data from Seurat object, I wonder which among raw counts and normalized data should I extract to use in tacco.
Although the result did not deviate much from each other's, I wanted to be sure which is right. 

Thank you!

**Comment by simonwm** [comment]
Hello,
Generally tacco assumes that both the reference data and the data to annotate are given as raw counts. For the default settings it is expected that you don't see a lot of differences between normalized data and raw counts, but this can be quite different, especially for wrapped third party methods.
