### ISSUE TITLE
Error caused by scipy version: 'csr_matrix' object has no attribute 'A'

### ISSUE THREAD

**Issue by Biogod2020** [simonwm/tacco#20]
Since the shorthand `.A `for convertomg the `csr_matrix` to `numpy.ndarray` has been deprecated in the latest version of `scipy`. Directly running the raw count for annotation would encounter this error message.

I solved this by modify the environment.yml to
`
name: TACCO_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>3.7.0,!=3.8.0
  - requests
  - joblib
  - numba>=0.51.2
  - numpy
  - matplotlib!=3.7.0
  - pyqt!=5.9.2
  - seaborn
  - sparse_dot_mkl>=0.7.3
  - scanpy>=1.7.0
  - statsmodels
  - anndata
  - pandas>=1.1.0
  - scipy==1.6.0
  - mkl
  - mkl-service
  - scikit-learn
  - threadpoolctl
  - pyamg
  - tacco

`

**Comment by JWatter** [comment]
Hi @Biogod2020,

Thanks for letting us know about the errors introduced by the upstream release of scipy!
We put out a new tacco release, see the [release notes](https://simonwm.github.io/tacco/release_notes/release_notes_0.4.0.html), which takes care off the deprecated functions and includes further maintenance.
The recommended way of installing is via conda again: `conda install -c conda-forge tacco`
