### ISSUE TITLE
Segmentation fault when running annotate

### ISSUE THREAD

**Issue by Laraine-Z** [simonwm/tacco#22]
Hello,
I am running TACCO with code below:
tc.tl.annotate(ad_sp,ad_sc,'bbknn_res.3',result_key='annotation')

It comes with the error log below:
Starting preprocessing
Annotation profiles were not found in `reference.varm["bbknn_res.3"]`. Constructing reference profiles with `tacco.preprocessing.construct_reference_profiles` and default arguments...
Finished preprocessing in 115.81 seconds.
Starting annotation of data with shape (17355, 18619) and a reference of shape (28998, 18619) using the following wrapped method:
+- platform normalization: platform_iterations=0, gene_keys=bbknn_res.3, normalize_to=adata
   +- multi center: multi_center=None multi_center_amplitudes=True
      +- bisection boost: bisections=4, bisection_divisor=3
         +- core: method=OT annotation_prior=None
mean,std( rescaling(gene) )  0.08640114514516119 0.40399216875327065
bisection run on 1
Segmentation fault

Could anyone help me to figure out the problem??

Thanks a lot!

**Comment by Laraine-Z** [comment]
The versions I used are as below:

python == 3.9.20
GCC == 13.3.0
tacco == 0.3.0 /0.4.0

**Comment by JWatter** [comment]
Hi!
Did you try it in a fresh conda environment, where you install "only" tacco? Sometimes the environment gets screwed up by installing different packages relying on different implementations for parallelization, like different BLAS or OpenMP libraries. These can then get mixed up and lead to weird behaviour like segfaults.
You could try to run it with a different number of cores, especially just a single core: This should use serial code paths in a lot of these libraries which should not lead to as much trouble.

Hope this helps!

**Comment by Laraine-Z** [comment]
Thanks for your reply~ 
At first I do create a new conda env with python 3.9.20(default) and install tacco only by pip, then I met the errors. Now I recreate the env with python 3.9.7 and reinstall tacco by conda, and it runs succesfully!

**Comment by Laraine-Z** [comment]
There is another problem I have encountered that I would like to know how to solve when I use :
tc.pl.scatter(ad_sp, keys='annotation', position_key=['x','y'],legend=True,point_size=1, noticks=True,joint=True,axes_labels=['X','Y'],render = False, rasterized =False)
plt.savefig(args.dataname+'_annotation.pdf')
plt.show

But, there is no legend in the result plot. Could you please help me to figure out the problem?

Thank you♥

**Comment by Laraine-Z** [comment]
Solved by "plt.savefig(args.dataname+'_annotation.pdf',bbox_inches='tight')"

**Comment by JWatter** [comment]
Glad it is solved!
