### ISSUE TITLE
Question regarding osmFISH mouse somato-sensory cortex

### ISSUE THREAD

**Issue by daaaaaaa64** [simonwm/tacco#6]
Hello,

I am running the tacco examples osmFISH mouse somato-sensory cortex with my own data, but the result file full_anno.csv of osmFISH_run_TACCO_segmentation.py contains only double the number of segmentations, what parameters can I change to make the segmentation more reasonable?

Thank you!

**Comment by simonwm** [comment]
Hello,

there are many options to tune the segmentation result (see the docs for [segment](https://simonwm.github.io/tacco/_autosummary/tacco.tools.segment.html#tacco.tools.segment) and [spectral_clustering](https://simonwm.github.io/tacco/_autosummary/tacco.tools.spectral_clustering.html#tacco.tools.spectral_clustering)). The best settings depend on the properties of your input dataset.

If your input dataset has a different density of molecules than the example, you might want to adjust `distance_scale` to compensate for this.
In general, you could tune the maximum size of the segmented objects measured as number of molecules per object with the `max_size` parameter: If you use a larger value for `max_size`, you also get less segmented objects.

Hope this helps!
