### ISSUE TITLE
Example request - Visium

### ISSUE THREAD

**Issue by cathalgking** [simonwm/tacco#8]
Would it be possible to show a simple example from a 10x Visium output from Space Ranger and how TACCO can interact with it? Even just read in and annotate the spatial data. I am having trouble with the formatting when following the ''Slide-Seq Mouse Colon'' and ''Mapping single cells into space'' tutorials at the tc.tl.annotate() step and the same method for a Visium would be useful to many.

**Comment by JWatter** [comment]
Hi @cathalgking, thanks for the suggestion! We plan to include a full Visium example in the next minor release. TACCO does not include IO features and relies on other packages for that. As soon as the data is in an anndata, the same [tc.tl.annotate](https://tc.tl.annotate/) call should just work. Here the essence of the example:

```
import anndata as ad
import squidpy as sq
import tacco as tc

# Load data with anndata and squidpy
adata_ref = ad.read_h5ad(<path/to/single/cell/reference/h5ad>)
adata_vis = sq.read.visium(<path/to/visium/spacerange/folder/>)
adata_vis.var_names_make_unique() 

# Annotate with TACCO
annotation_key = 'celltype' # categorical obs key in adata_ref
result_key = 'celltype_annotated' # new compositional obsm key in adata_vis
tc.tl.annotate(adata_vis, adata_ref, annotation_key=annotation_key, result_key=result_key)
```

I hope that helps!

**Comment by cathalgking** [comment]
Thanks @JWatter

**Comment by cathalgking** [comment]
@JWatter Is a single-cell reference absolutely required for using TACCO? Or can it be ran reference free?

**Comment by cathalgking** [comment]
@JWatter How can I use your above example to plot the Visium image? I am testing this with a public single-cell reference and when I try to plot the image with TACCO scatter or heatmap, the image is not shown. Ideally, I would like a visium image with the spots or group of spots annotated, if there is a function that can show that? Thanks

**Comment by JWatter** [comment]
Regarding your second comment:
As Tacco is agnostic about the details of the method producing the data, it does not support "special features" of individual experimental methods (at least not yet). And having a matching H&E image associated with expression data is not a generic feature of all spatial omics methods. But other tools have specialized functionality for this. If you already used squidpy for reading the Visium data (as suggested in the example above), then you might want to check out their plotting capabilities. AFAIK they can plot categorical annotation on top of an H&E image. You can extend the Visium example above by
```
# generate categorical majority annotation from compositional annotation
categorical_key = 'maximum_celltype' # new categorical obs key in adata_vis
tc.utils.get_maximum_annotation(adata_vis, result_key, result_key=categorical_key)
# plot categorical annotation on top of H&E image
sq.pl.spatial_scatter(adata_vis, color=categorical_key)
```

Hope this helps!

**Comment by cathalgking** [comment]
Thanks @JWatter for the above info. I ran through a Visium dataset according to the example. It seems as if the annotations were transferred to the Visium image as shown below. However, is it possible to calculate a confidence score for each label? some metric to associate each label transferred with the spatial spot as in the below image. The vast majority of spots here seem to be associated with the same label. Of course it depends on the input single-cell reference, but is there a way to then filter annotations based on that confidence score?
Also, your example did not include any clustering. Does that not matter for the TACCO label annotation? Or should the data have been ran through some clustering algorithm beforehand?

`
import anndata as ad
import squidpy as sq
import tacco as tc

# Load data with anndata and squidpy
adata_ref = ad.read_h5ad("/PATH/tabula-muris-senis-droplet-processed-official-annotations-Large_Intestine.h5ad")
adata_ref

A1 = sc.read_visium(path="/PATH/A1/outs",
                          count_file='filtered_feature_bc_matrix.h5')
#
A1.var_names_make_unique() 

# Annotate with TACCO
annotation_key = 'cell_ontology_class' # categorical obs key in adata_ref
result_key = 'celltype_annotated' # new compositional obsm key in adata_vis
tc.tl.annotate(A1, adata_ref, annotation_key=annotation_key, result_key=result_key)

categorical_key = 'maximum_celltype' # new categorical obs key in adata_vis
tc.utils.get_maximum_annotation(A1, result_key, result_key=categorical_key)
# plot categorical annotation on top of H&E image
#sq.pl.spatial_scatter(A1, color=categorical_key)
sc.pl.spatial(A1, color=categorical_key, bw=True, palette='Paired')`

<img width="958" alt="Screen Shot 2023-08-27 at 5 53 14 pm" src="https://github.com/simonwm/tacco/assets/32261323/62cec51b-07b7-4147-9c65-2249e746f06f">

**Comment by JWatter** [comment]
Re compositional VS categorical annotation: As hinted to in the example, TACCO (like all other annotation transfer methods for mixtures) generates a compositional annotation. That means that we assign fractions of the annotation categories to each observation. E.g., most of your Visium spots contain contributions of multiple different cell types. To plot compositional annotations we provide the [tc.pl.scatter](https://tc.pl.scatter/) function. But as you realized before, this does not plot H&E images. Squidpy on the other hand can plot H&E images, but on top of that only multiple categorical annotations simultaneously or one continuous annotation per plot, but not compositional annotation. The line `tc.utils.get_maximum_annotation(A1, result_key, result_key=categorical_key)` takes the compositional annotation output from TACCO and creates a categorical annotation from it, i.e. it takes only the majority celltype per spot and forgets about the rest. Then it is not unexpected to be left with the majority celltype of the reference. As proxy for a categorical confidence you can take the compositional cell type fraction for the majority type. For more discussion about compositional VS categorical annotation I recommend checking out the TACCO paper.

**Comment by JWatter** [comment]
Re clustering: Clustering is not a value on its own, but a means to achieve something. One could do a clustering e.g. on top of cell type fractions (i.e. the compositional annotation result), or on top of the expression directly factoring in spatial proximity between spots to get a region annotation. This can be done done with TACCO (and other tools as well) to get some flavor of region annotation. Check out e.g. https://simonwm.github.io/tacco/notebooks/slideseq_mouse_colon.html#Find-spatially-contiguous-regions-of-comparable-expression-patterns to get an example for finding regions in a similar dataset.

**Comment by Rafael-Silva-Oliveira** [comment]
> Regarding your first comment: Some reference is always required: the method has to know what it should annotate. But that reference does not need to be a single cell RNA seq dataset. In principle, reference profiles in the `.varm` slot of an otherwise empty reference AnnData would be enough to create a working reference. A little less hacky way would be to create a fresh anndata with the profiles of the cell types instead of cells and add a `.obs` column containing the cell types of these profiles. You can also add multiple representative profiles per cell type as "cells". Tacco would then automatically populate the `.varm` slot and run the annotation. So a single-cell reference is not absolutely required for annotation with Tacco, but highly recommended.
> 
> Here is a quick pseudocode as starting point for experiments with a self-made marker-based reference:
> 
> ```
> # adata is the data to annotate
> # create profiles for your annotations
> # the closer the profiles match those appearing in your data, the better the annotation will be
> # if you can get them from FACS sorted bulk sequencing that should be a good reference, too.
> cell_types = ['typeA','typeB','typeC']
> reference_profiles = pd.DataFrame(0.0,index=cell_types,columns=adata.var.index)
> reference_profiles.loc['typeA', ['SAMD11', 'NOC2L', 'KLHL17']] = [42.0, 17.0, 73.0] # replace with real marker genes 
> reference_profiles.loc['typeB', ['SAMD11', 'NOC2L', 'PLEKHN1']] = [5.0, 32.0, 23.0]
> reference_profiles.loc['typeC', ['PLEKHN1', 'PERM1']] = [12.0, 9.0]
> # create a reference from your profiles
> reference = ad.AnnData(reference_profiles)
> reference.obs['cell_type'] = reference_profiles.index
> # treat it similar to a regular single cell reference (some annotation methods might have issues with it...)
> tc.tl.annotate(adata, reference)
> ```

Hi @JWatter 

What exactly would bet the values for this reference profile?

If we have 12 cell types, according to your example, would we then have 12 rows (celltypes) and then the columns would be the markers for all cell types? And the dataframe values, would be the sum of counts for any given cell type for a given marker?

Thanks

**Comment by JWatter** [comment]
Hi @Rafael-Silva-Oliveira,

You can set the values of the reference however you like. For example just write a 1 when the marker gene corresponds to that specific cell type, and 0 otherwise. If you have a reason to believe that the counts for some marker gene might be higher than those for another one in a certain cell type, then you can enter those values as well. This information can come from a reference data set, e.g. scRNA seq or FACS sorted bulk RNA seq. But this information cannot be straightforwardly taken from the spatial data which you want to annotate.

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi @Rafael-Silva-Oliveira,
> 
> You can set the values of the reference however you like. For example just write a 1 when the marker gene corresponds to that specific cell type, and 0 otherwise. If you have a reason to believe that the counts for some marker gene might be higher than those for another one in a certain cell type, then you can enter those values as well. This information can come from a reference data set, e.g. scRNA seq or FACS sorted bulk RNA seq. But this information cannot be straightforwardly taken from the spatial data which you want to annotate.

Perfect, I'll give it a shot! Yeah, just after reviewing what I posted, doesn't make much sense to give an example with the ST data that I want to annotate (should've used the scRNA reference instead!). Thank you again :)
